export const AppPaths = {
  dashboard: '/',
  exercises: '/exercises',
  foods: '/foods',
  media: '/media',
  soldiers: '/soldiers',
  accounts: '/accounts',
  garments: '/garments',
  trainers: '/trainers',
  trainerSubscriptions: '/trainers/subscriptions',
  userSessions: '/user-sessions',
  notificationTemplates: '/notifications/templates',
  sendNotification: '/notifications/send',
  login: '/auth/login',
  accessDenied: '/auth/access-denied',
  error: '/auth/error',
  notFound: '/not-found',
} as const;
